name: Feature Request
description: Suggest a new feature for XAI Explorer
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      options:
        - Block View
        - Transaction View
        - Address/Account View
        - Validator Dashboard
        - Search
        - API
        - UI/UX
        - Other
    validations:
      required: true
